### ISSUE TITLE
pomo list doesn't work without colors

### ISSUE THREAD

**Issue by strogiyotec** [kevinschoon/pomo#33]
@kevinschoon  Found one bug
Here is my config.json
```
{
}
```
So it's empty. When I run `pomo list` I got this error 
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x62efaf]

goroutine 1 [running]:
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc00009b230, 0x719c60, 0xb0aed0)
        /home/strogiyotec/go/pkg/mod/github.com/jawher/mow.cli@v1.0.4/internal/flow/flow.go:39 +0xd4
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc00009b320, 0x719c60, 0xb0aed0)
        /home/strogiyotec/go/pkg/mod/github.com/jawher/mow.cli@v1.0.4/internal/flow/flow.go:29 +0xb6
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc00009b410, 0x719c60, 0xb0aed0)
        /home/strogiyotec/go/pkg/mod/github.com/jawher/mow.cli@v1.0.4/internal/flow/flow.go:29 +0xb6
github.com/jawher/mow.cli/internal/flow.(*Step).callDo.func1(0xc00009b440, 0x0, 0x0)
        /home/strogiyotec/go/pkg/mod/github.com/jawher/mow.cli@v1.0.4/internal/flow/flow.go:52 +0x4e
panic(0x719c60, 0xb0aed0)
        /usr/lib/go-1.15/src/runtime/panic.go:969 +0x175
```
I checked, the problem is in util.go

```
if color := config.Colors.Get(tag); color != nil {
```
So if Colors are nil then it fails. Is it expected behavior or a bug ? If it's a bug then I make a PR, it shouldn't be hard just add additional condition

**Comment by strogiyotec** [comment]
Fixed here https://github.com/kevinschoon/pomo/pull/34
