### ISSUE TITLE
Null ptr when pomo list is executed

### ISSUE THREAD

**Issue by strogiyotec** [kevinschoon/pomo#40]
@kevinschoon  hey , during refactoring for more test friendly code you made a small bug. How to reproduce.
Run `pomo list` the output is 
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x639f2c]

goroutine 1 [running]:
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc0000751d0, 0x718ea0, 0xb09ed0)
        /home/strogiyotec/go/pkg/mod/github.com/jawher/mow.cli@v1.0.4/internal/flow/flow.go:39 +0xd4
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc0000752c0, 0x718ea0, 0xb09ed0)
        /home/strogiyotec/go/pkg/mod/github.com/jawher/mow.cli@v1.0.4/internal/flow/flow.go:29 +0xb6
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc0000753b0, 0x718ea0, 0xb09ed0)
        /home/strogiyotec/go/pkg/mod/github.com/jawher/mow.cli@v1.0.4/internal/flow/flow.go:29 +0xb6
github.com/jawher/mow.cli/internal/flow.(*Step).callDo.func1(0xc0000753e0, 0x0, 0x0)
        /home/strogiyotec/go/pkg/mod/github.com/jawher/mow.cli@v1.0.4/internal/flow/flow.go:52 +0x4e
panic(0x718ea0, 0xb09ed0)
        /usr/lib/go-1.15/src/runtime/panic.go:969 +0x175
github.com/kevinschoon/pomo/pkg/cmd.list.func1.1()
        /home/strogiyotec/IdeaProjects/GoLang/my_pomo/pomo/pkg/cmd/cmd.go:167 +0xac

```
The reason
```
func Run() { New(nil).Run(os.Args) }
```
You passes nil as a config option. I will fix it with my refactored version of delete multiple task branch

**Comment by kevinschoon** [comment]
Thanks @strogiyotec, I fixed it in 28b2e14!
